### ISSUE TITLE
Feature request: allow custom icons for items

### ISSUE THREAD

**Issue by MinehubDE** [TomBursch/kitchenowl#111]
### What's the feature 🧐

Currently, items put into the shopping list do not have visible icons as they are available in "bring!"
![image](https://user-images.githubusercontent.com/43423944/208314963-0dda3362-df60-4a99-85bd-7dfb557e7689.png)

Such icons would improve the user experience a lot.
It would be perfect to have those items pre-installed when running the environment the first time.
For new items, a custom upload of such icons should be possible.

**Comment by irishrain** [comment]
The icons in the categories are simply emojis, you can add them to your custom categories as well.

**Comment by MinehubDE** [comment]
You are right, I'm just stupid.
I removed the category icons request from the issue.

**Comment by c0bnut** [comment]
This is the only thing holding me out from switching from Bring!

**Comment by TomBursch** [comment]
I think there are two things blocking this right now:
- The icons: getting a good collection of that many icons won't be easy and my design skills are limited. 
- Right now you essential start with an empty item database. There are a few things that come to my mind to solve this:
  - ~We restructure some parts to allow for more complex initial items (When you select or add a language to your server) where they have assigned images~ (Done)
  - We create a system that maps item names to images and use this to set the item's image on creation/regularly
  - We start blank and the user has to select an image for each item by hand

For now we could start with the third option and improve from there, since none of them exclude each other.

**Comment by TomBursch** [comment]
I think there are two things blocking this right now:
- The icons: getting a good collection of that many icons won't be easy and my design skills are limited. 
- Right now you essential start with an empty item database. There are a few things that come to my mind to solve this:
  - We restructure some parts to allow for more complex initial items (When you select or add a language to your server) where they have assigned images
  - We create a system that maps item names to images and use this to set the item's image on creation/regularly
  - We start blank and the user has to select an image for each item by hand

For the now we could start with the third option and improve from there, since none of them exclude each other.

**Comment by irishrain** [comment]
I searched for free icon sets, but they mostly focus on technology, there are a few food things here and there, but nowhere close to enough. What do you think about creating icons with stable diffusion? I'm not sure about license issues, but if you are open for this I would offer to try if this is a feasible option.

**Comment by TomBursch** [comment]
@irishrain I looked through some sets as well and you're right there all not great. Using multiple sets also comes with the problem of design discrepancies. Stable diffusion could be an option but I'd prefer using SVGs for the icons. Maybe there is some tool to generate SVG from the SD results? Otherwise I might be able to find an artist willing to help.

Edit: Maybe this could work: https://github.com/GeorgLegato/Txt2Vectorgraphics

**Comment by irishrain** [comment]
> Edit: Maybe this could work:
> https://github.com/GeorgLegato/Txt2Vectorgraphics

This is exactly what I had in mind. I will give it a try sometime this week and post some example results here, then you can decide what route to go

**Comment by c0bnut** [comment]
Would you consider using icons8? https://icons8.com/license
Free to use, the only requirement of the license is to link to their website in the about section of the app.

**Comment by irishrain** [comment]
So, I had a go with stable diffusion. I chose the nine ingredients from the original example in the feature request as my test ingredients. It turns out Txt2Vectorgraphics comes with 10 different presets, and by reading up on the vectorization process, the underlying tool potrace has two basic operation modes (applying a threshold, then vectorizing or detecting edges, then applying a threshold, then vectorizing), in addition I also found https://github.com/visioncortex/vtracer which creates greyscale or color svg files.
Because stable diffusion results depend on a seed, I generated images for each of the ingredients with 16 different consecutive seeds to give an impression of the bandwidth of results.
Multiplying this all out I now have 5760 svg files, sorted into folders by ingredient, then subfolders by preset, then with suffixes for the different vectorization method. The compressed zip file has 680 MB.
Any idea how I can best share this?

**Comment by TomBursch** [comment]
@irishrain Wow thanks for the work! Could you text me on matrix? I can provide you with a dropbox file request link where you can upload the zip. Or alternatively you could create a public git repo and put everything in there.

**Comment by TomBursch** [comment]
First, thanks to @irishrain for generating the icons. Just to give everyone an update, I looked through all of them, and the results were okay, but definitely needed some manual labor to get them to a state where I'd use them. Thus, I decided to use icons8.

I've also got a working version of it. There are still some things left to do, but it should be ready for the next release.

![Screenshot from 2023-03-02 20-19-33](https://user-images.githubusercontent.com/9092682/222532279-1b49b66b-899e-484c-b2af-a190b2272a75.png)
