### ISSUE TITLE
Bug: Unraid: KitchenOwl frontend "Hmmmm. server can't be reached"

### ISSUE THREAD

**Issue by nath2125** [TomBursch/kitchenowl#112]
### Is this urgent?

No

### What parts are affected

Frontend

### What are the Server/Client versions of KitchenOwl

Should be latest

### What's the problem 🤔

Hi there, 

Using unraid as the os and downloaded the KitchenOwl server and web client from the community app store.

Front end web says "Hmmmm. server can't be reached". will also list the configuration for both web and server containers.
![6](https://user-images.githubusercontent.com/99367069/209759641-613be716-2b48-480c-810d-41e3dfab8758.PNG)
![7](https://user-images.githubusercontent.com/99367069/209759794-81774936-97e8-43fb-a815-49ebd1a9b5ad.PNG)
![8](https://user-images.githubusercontent.com/99367069/209759817-be4ecb84-8013-4b40-a244-cea92241fa5b.PNG)

**Comment by TomBursch** [comment]
I'm not maintaining the unraid template but the kitchenowl service port is wrong. Can you bind port 5000 to the container port 5000, instead of 80? Kitchenowl web connects via the uwsgi protocol instead of http, which the backend provides on port 5000. 

https://github.com/TomBursch/kitchenowl-backend/blob/main/docker-compose.yml

**Comment by nath2125** [comment]
I will give it a go see if I can. Otherwise I might have to put it into portainer or something else

**Comment by nath2125** [comment]
ok sure enough it works. Thanks a lot for your help

**Comment by r0mee** [comment]
this also helped me, may have to ask the maintainer to fix this.
