### ISSUE TITLE
Feature request: Categorize recent items

### ISSUE THREAD

**Issue by TomBursch** [TomBursch/kitchenowl#149]
> Having the complete recent items list there, even with the category structure would be awesome. 
Most of the time we are buying the same stuff again and it's much more comfortable to go through a list to check what is missing / needed.
>
> Thank you for this great project!

_Originally posted by @kebbe in https://github.com/TomBursch/kitchenowl/issues/125#issuecomment-1432630058_

**Comment by Nyokkai** [comment]
I feel like this would be a really really useful enhancement to the app. As Kebbe said, most of the time we're buying the same stuff again and again so it'd be great to have the entire recent items list there, instead to have it limited to only 30 items max, that way it'd be a lot easier to make the shopping list anytime without forgetting anything.

Currently I have all of my shopping items listed in the app but I can't use it as intended because I'm afraid of surpassing the 30 items when checking the items I'm buying when I'm at the market, because next time I'm making the list I'm gonna forget to put those items that I'm not seeing in the recent items list.

So far I'm loving the app but this would be a huge QoL change!! Thank you!!
