### ISSUE TITLE
Feature request: Persist already created checklist when disconnected from server in android app

### ISSUE THREAD

**Issue by pancho-villa** [TomBursch/kitchenowl#24]
### What's the feature 🧐

Hello,

Great app, I love it! I can't use it until I can resolve the ability to create lists online and use them offline from the server. I'm not sure if this is a bug or a feature request, but it appears the backend needs internet access to the world to use the Android app checklist feature. When you lose connection to the server it switches to offline mode and loses all the items in the default check list.

### Extra information and references

Other than that, I love it, keep up the great work, and thank you!

**Comment by TomBursch** [comment]
Hey, thanks for the kind words! Not sure if I understand the issue correctly. Do you mean that when offline the item search is not suggesting items and only displaying what you're typing in the search bar? If so, that is currently by design. But I would like to have that changed in the future as well. Will put it on the list. Thank you for the contribution!

**Comment by pancho-villa** [comment]
I think it works as expected and I made a mistake. Originally when I tested what happens if you disconnect from the server I thought the checklist items disappeared, but that's not the case. Items do disappear from the list once you select them tho, and I would like the green boxes to turn grey when the checklist goes into offline mode. But I can live with its current behavior.

Thanks again, and go ahead and close this feature request.
