### ISSUE TITLE
Feature request: UI/UX more clear between shopping list and recent items in list-mode

### ISSUE THREAD

**Issue by crosspolar** [TomBursch/kitchenowl#323]
### What's the feature 🧐

While the grid is easy to distinguish between the shopping list and the recent items at the bottom, for the list it is not (as already mentioned in #179). I suggest having more alpha on the recent items and will provide a PR, but of course I'm open to your ideas or if it is agains the color palette.

**Comment by Radoom** [comment]
Adding on this one:
Preferring the "list" view, both in desktop browser and in android app, too. In GRID view, items to get are highlighted in the accent color, e.g. bright green, on both platforms. In LIST mode however, "recent items" are just a bit darker, but colors are not applied to the "active" items at all. 
Expected behavior would be to have it "bright green" or whatever color is chosen as in grid view also in list view.

Sidenote: using the "confirm" setting instead of "tap" seems to have a small bug. 

1. Have items on the "active" list.
2. Tap one or more => they get a tick mark, and their text color changes to the highlight/accent color, and the "confirm double-tick mark button appears (OK up to here)
3. Tap the double-tick mark button. Items move down to "recent items" section, but they **keep** their background color entirely (text goes back to grey), so they look exactly the same as the "active" items.
4. Pull down on the screen to refresh => **now** the background color of the "recent items" get darker.

In Grid View, problem does not exist: In step 2 above, tiles background goes grey immediately when tapped, and stay that way once in 3 above the confirmation button is pressed and they move to "recent items". However, as the highlight color on grid view is honored, issue for list view would likely be solved the moment colors are honored for active items there, too.
