### ISSUE TITLE
Feature request: Offer dropdown for adding ingredients to specific shopping list from recipe view

### ISSUE THREAD

**Issue by schnillerman** [TomBursch/kitchenowl#333]
### Is this urgent?

Yes

### What parts are affected

Frontend

### What is the server version

public/official server

### What is the client version

0.4.20 Android

### What's the problem 🤔

Adding ingredients from a recipe puts them in a random shopping list. If different shopping lists exist, ask for target list, e.g. by means of a dropdown list next to the add button. Default list would be the first in list of shopping lists. (See also #332).

**Comment by TomBursch** [comment]
The current behavior is to add recipe items to the first shopping list. I'm not sure what the best behavior would be because asking for the shopping list every time could be annoying. We only have two shopping lists, one for groceries and one for hygienics, and we would never add recipe items to the other list. Do you have a specific workflow in mind?

**Comment by schnillerman** [comment]
I do have different lists for butcher, groceries, vegetables and so on because mostly different shops.

A drop-down beneath or next to "add to list" button could be an option. You could de-select some items, add the rest to a list easily, then add the previously de-selected ones to another list.

Speaking of that, an invert selection button might make sense 😂
