### ISSUE TITLE
Bug: deleting categories leads to broken system: cannot add categories anymore. Household not accessible anymore thru webapp.

### ISSUE THREAD

**Issue by tlwt** [TomBursch/kitchenowl#410]
### Is this urgent?

Yes

### What parts are affected

Both

### What is the server version

v94

### What is the client version

v0.4.21 (92)

### What platform are you using

iOS

### What's the problem 🤔

I have a shared household and my wife wanted to update the categories and delete a few. While deleting the first categories the entire settings section went empty. We are not able to create new categories anymore. 

Looking to the shopping list we still see the categories, but only on our phone. The web-app does not even display our household anymore. 

I wanted to export the data to check for any errors, but the export button is also not working. The import button still works. 

![IMG_2EB99C9BA4C8-1](https://github.com/TomBursch/kitchenowl/assets/8267086/bae9f6d3-67eb-4f82-85f4-18827ab986d5)
![IMG_CF4BAF834120-1](https://github.com/TomBursch/kitchenowl/assets/8267086/b919bd55-4a87-4fcc-a6fb-aa4231cebc86)
![Bildschirmfoto 2024-03-01 um 17 43 17](https://github.com/TomBursch/kitchenowl/assets/8267086/6bbba65e-5b06-4297-ae8d-0f4109e3db10)

### Share your configuration

```yml
Using hosted version
```

**Comment by TomBursch** [comment]
Looking through the logs, it looks like you deleted your household 🤔 The app is just displaying the cached version of it. Can you recall what exactly you did? Because I cannot reproduce this by just deleting/renaming/merging categories or doing anything else in the settings.

I tried restoring it, but sadly, your household is not yet included in the latest backup.

**Comment by tlwt** [comment]
That might have happend by accident. No big harm done. I'll just set it up again. To turn this into a feature request: separate the export / import / delete settings from the category management. 

Anyhow - really great app! Appreciate all the work you put into it. Have a great weekend.

**Comment by TomBursch** [comment]
Yeah I figured the household wasn't old. First thing I did after I read this issue was implementing soft deletion of households, keeping them for max 30 days before they are completely removed. Deleting a household already is two clicks, you're asked to confirm it. But I guess there could be more separation between deleting and exporting.

And thanks for the kind words!
