### ISSUE TITLE
Feature request: Make JWT_REFRESH_TOKEN_EXPIRES editablee

### ISSUE THREAD

**Issue by shangri26199** [TomBursch/kitchenowl#484]
### What's the feature 🧐

Currently the lifetime of a JWT Token is hardcoded to 30days. Please make it a variable just like the JWL_SECRET_KEY.

In a bigger feature the OAuth token could request a refresh token. You could set the time then in your OAuth provider

### Extra information and references

current omega clean workaround to do this on every container restart. appended to back in docker-compose.yml:
    command:
      - -c
      - |
        sed -i 's/JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=30)/JWT_REFRESH_TOKEN_EXPIRES = timedelta(days=180)/' /usr/src/kitchenowl/app/config.py
        grep JWT_REFRESH_TOKEN_EXPIRES /usr/src/kitchenowl/app/config.py
        ./entrypoint.sh --ini wsgi.ini:web --gevent 200

**Comment by TomBursch** [comment]
Did you encounter any problems with your refresh tokens? Because the 30 days shouldn't normally be a problem. I've implemented [refresh token rotation](https://auth0.com/docs/secure/tokens/refresh-tokens/refresh-token-rotation), every time you request a new access token you also get a new refresh token that is then valid for 30 days again. This means you will only be logged out if you haven't used the App for 30 days. 

Regarding OAuth, right now, the token returned by OAuth is only used once when the user authenticates himself. If you remove the OAuth user, the KitchenOwl user is not removed and stays logged in.

**Comment by shangri26199** [comment]
My knowledge about OAuth is really basic, just learning things as i try to use them.
I've got an authentik instance that does the OAuth part for my kitchenowl.
In authentik i can see an access token that is provided when logging in, which has a lifetime of 5minuten (default).
There is also a section for refresh tokens, but my authentik does not list any. So I'm not sure, if an refresh token is requested/granted.
I've increased the lifetime of these refresh tokens, but since i do not see if any tokens are granted I've dig through the repository and saw the hardcoded $JWT. Possible I've fixed everything with increasing refreshtoken lifetime.

I've allready noticed that my kitchenowl session is bound to an local storage token when using the web version in firefox.
How is it implemented for the android/ios app?
My girlfriend and i are using the app on different devices. Often i do the shopping, but when she does after like 2 months she needs to relog, including 2FA and stuff. Thats good but kinda anoying and why i wanted to increase the lifetime ;)

**Comment by TomBursch** [comment]
Yes, makes sense to be able to change it if your partner uses it rarely to avoid getting logged out. 

I'm not sure of some parts of OIDC either. I don't request refresh tokens since I never update the user from the OAuth provider. This makes sense in the case of e.g. Google since you don't care if the OAuth account still exists in the future and only care about it during login. For self-hosters this means deleting the OAuth account won't delete the KitchenOwl account, though. 

Yes, the refresh token is encrypted and stored (both in the browser and in the mobile app)
