### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [TomBursch/kitchenowl#75]
### What's the feature 🧐

@TomBursch 

https://hosted.weblate.org/projects/kitchenowl/#information
was just licensed AGPLv3-only.

Instead of requiring the consent of all translators to go AGPLv4 down the road,
it is usually the case that -only is selected by accident.

It can be changed in
https://hosted.weblate.org/settings/kitchenowl/kitchenowl/
https://hosted.weblate.org/settings/kitchenowl/glossary/

The repo doesn't appear to say if it is one way or the other already.

### Extra information and references

>If the Program specifies that a certain numbered version of the GNU Affero General
Public License "or any later version" applies to it, you have the
option of following the terms and conditions either of that numbered
version or of any later version published by the Free Software
Foundation.

**Comment by TomBursch** [comment]
Yes I just changed it to AGPLv3-only to match the license of this repository. It was Apache 2.0 before which was done by mistake. Although if I understand it correctly all previous translations are technically still in that License because the authors haven't consented to that change? I wanted to make sure that future translations have the correct license. I'll change it to AGPLv3 or later and will look into changing that for this repository as well.

**Comment by comradekingu** [comment]
@TomBursch
Great.
The strings up until now are effectively dual-licensed.
The Apache 2.0 license is a weak permissive license that allows for this.
Similarly translators can take their Apache 2.0 strings and do anything short of violating patents with them.

You can just ask all code contributors for consent to license to AGPLv3+-or-later to be on the safe side.
